Repository PeanutCoffee/MiniProjects, pull requests merged in 2022-10, with the labels that each got.

#4 Added styles for Jokes Chrome Extension
  Jokes Chrome Extension/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#6 Added script.js for Jokes Chrome Extension
  Jokes Chrome Extension/script.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#8 Added manifest and logo for Jokes Chrome Extension
  Jokes Chrome Extension/favicon.ico
  Jokes Chrome Extension/logo.png
  Jokes Chrome Extension/manifest.json
Labels: enhancement, good first issue, hacktoberfest-accepted

#12 Verilog Codes for Adder #11
  Jokes Chrome Extension/script.js
  Jokes Chrome Extension/styles.css
  Verilog Codes for Hardware Modelling/adder
  Verilog Codes for Hardware Modelling/adder.v
  Verilog Codes for Hardware Modelling/adder_tb.v
  Verilog Codes for Hardware Modelling/alu.vcd
Labels: enhancement, good first issue, hacktoberfest-accepted

#14 NewsApp using tkinter in Python
  NewsApp/News.py
Labels: enhancement, hacktoberfest-accepted

#16 Fix issue 15 counter
  Verilog Codes for Hardware Modelling/counter.v
  Verilog Codes for Hardware Modelling/counter_tb.v
Labels: enhancement, hacktoberfest-accepted

#18 Solved Isseue #15
  Verilog Codes for Hardware Modelling/4x1.v
  Verilog Codes for Hardware Modelling/fsm.v
Labels: enhancement, hacktoberfest-accepted

#20 Resolved Issue #9
  Verilog Codes for Hardware Modelling/1x2_behavioural.v
  Verilog Codes for Hardware Modelling/1x2_dataflow.v
  Verilog Codes for Hardware Modelling/1x2_gatelevel.v
  Verilog Codes for Hardware Modelling/1x2_tb.v
  Verilog Codes for Hardware Modelling/1x8_structural.v
  Verilog Codes for Hardware Modelling/1x8_tb.v
  Verilog Codes for Hardware Modelling/main
  Verilog Codes for Hardware Modelling/main.v
  Verilog Codes for Hardware Modelling/tb.v
Labels: enhancement, hacktoberfest-accepted

#22 instaProfile with Python
  instaProfile.py
Labels: enhancement, hacktoberfest-accepted

#24 Audio Recorder using Python
  audioRecorder.py
Labels: enhancement, hacktoberfest-accepted

#26 Resolved issue #25 Shift Registers
  Verilog Codes for Hardware Modelling/pipo
  Verilog Codes for Hardware Modelling/pipo.v
  Verilog Codes for Hardware Modelling/pipo_tb.v
  Verilog Codes for Hardware Modelling/sipo
  Verilog Codes for Hardware Modelling/sipo.v
  Verilog Codes for Hardware Modelling/sipo_tb.v
Labels: enhancement, hacktoberfest-accepted

#33 passage-counter index js
  passage-counter/index.js
  passage-counter/station.jpg
Labels: enhancement, hacktoberfest-accepted

#36 word to pdf with python
  wordtopdf.py
Labels: enhancement, hacktoberfest-accepted

#38 Movie Search App using React
  Movie Search/README.md
  Movie Search/package-lock.json
  Movie Search/package.json
  Movie Search/public/FilmFest.png
  Movie Search/public/favicon.ico
  Movie Search/public/index.html
  Movie Search/public/manifest.json
  Movie Search/public/robots.txt
Labels: enhancement, hacktoberfest-accepted

#39 Complete movie search app
  Movie Search/src/App.css
  Movie Search/src/App.js
  Movie Search/src/Footer.jsx
  Movie Search/src/Logo.png
  Movie Search/src/MovieCard.jsx
  Movie Search/src/index.js
  Movie Search/src/search.svg
Labels: enhancement, hacktoberfest-accepted

#41 YouTube Clone structure
  Jokes Chrome Extension/logo.png
  Movie Search/public/FilmFest.png
  Youtube Clone/index.html
  Youtube Clone/main.js
  Youtube Clone/styles.css
Labels: enhancement, hacktoberfest-accepted

#43 General Store Management System
  General Store Management System/store.cpp
Labels: enhancement, hacktoberfest-accepted

#45 stone_paper_scissor.cpp
  Game/stone_paper_scissor.cpp
Labels: enhancement, hacktoberfest-accepted

#48 guess_the_number.cpp
  Game/guess_the_number.cpp
Labels: enhancement, hacktoberfest-accepted

#46 flappybird game
  pyGAME-main/flappy_bird.py
  pyGAME-main/main.py
  pyGAME-main/sprites/background.png
  pyGAME-main/sprites/base.png
  pyGAME-main/sprites/gameover.png
  pyGAME-main/sprites/message.png
  pyGAME-main/sprites/pipe.png
  pyGAME-main/sprites/player.png
Labels: enhancement, good first issue, hacktoberfest-accepted

#51 Added accepted PR screenshot and badge
  README.md
  accepted.JPG
  badge level 4.png
  badge level 4.webp
Labels: enhancement

#49 Create Bank_Management_System.py
  Bank_Management_System.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#54 orphanage_management.cpp
  Orphanage Management/orphanage.cpp
Labels: enhancement, hacktoberfest-accepted

#60 Ping-pong.py
  Game/Ping-pong.py
Labels: enhancement, hacktoberfest-accepted

#62 Playing-cards.py
  Game/Playing-cards.py
Labels: enhancement, hacktoberfest-accepted

#65 school_management.py
  School Management/school_management.py
Labels: enhancement, hacktoberfest-accepted

#68 alarm-clock.py
  Alarm Clock/alarm-clock.py
Labels: enhancement, hacktoberfest-accepted

#69 Added Biometric Authentication App
  Biometric/.gitignore
  Biometric/.idea/.gitignore
  Biometric/.idea/compiler.xml
  Biometric/.idea/gradle.xml
  Biometric/.idea/misc.xml
  Biometric/README.md
  Biometric/URL Shortener System Design.md
  Biometric/app/.gitignore
  Biometric/app/build.gradle
  Biometric/app/proguard-rules.pro
  Biometric/app/src/androidTest/java/com/example/biometric/ExampleInstrumentedTest.kt
  Biometric/app/src/main/AndroidManifest.xml
  Biometric/app/src/main/java/com/example/biometric/MainActivity.kt
  Biometric/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Biometric/app/src/main/res/drawable/ic_baseline_fingerprint_white.xml
  Biometric/app/src/main/res/drawable/ic_launcher_background.xml
  Biometric/app/src/main/res/drawable/lock.png
  Biometric/app/src/main/res/drawable/yellow.jpg
  Biometric/app/src/main/res/layout/activity_main.xml
  Biometric/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Biometric/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Biometric/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Biometric/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Biometric/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Biometric/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Biometric/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Biometric/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Biometric/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Biometric/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Biometric/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Biometric/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Biometric/app/src/main/res/values-night/themes.xml
  Biometric/app/src/main/res/values/colors.xml
  Biometric/app/src/main/res/values/strings.xml
  Biometric/app/src/main/res/values/themes.xml
  Biometric/app/src/main/res/xml/backup_rules.xml
  Biometric/app/src/main/res/xml/data_extraction_rules.xml
  Biometric/app/src/test/java/com/example/biometric/ExampleUnitTest.kt
  Biometric/build.gradle
  Biometric/gradle.properties
  Biometric/gradle/wrapper/gradle-wrapper.jar
  Biometric/gradle/wrapper/gradle-wrapper.properties
  Biometric/gradlew
  Biometric/gradlew.bat
  Biometric/settings.gradle
Labels: enhancement, hacktoberfest-accepted

#72 Url Shortner Webapp using Python and Flask
  URL SHORTNER/aoo.py
  URL SHORTNER/templates/base.htm
  URL SHORTNER/templates/home.htm
  URL SHORTNER/templates/shorturl.htm
  URL SHORTNER/urls.db
Labels: enhancement, hacktoberfest-accepted

#74 Eye filter
  Eye Filter/Blue2.png
  Eye Filter/blue.png
  Eye Filter/haarcascade_eye.xml
  Eye Filter/test.py
Labels: enhancement, hacktoberfest-accepted

#80 Added analog Clock made using HTML, CSS & JS
  Analog Clock/Clock.jpg
  Analog Clock/clock.js
  Analog Clock/index.html
  Analog Clock/style.css
Labels: enhancement, hacktoberfest-accepted

#86 Update regarding issue #78
  image_compressor_py/README.md
  image_compressor_py/script.py
Labels: enhancement, hacktoberfest-accepted

#89 Python script for QR Code Generation
  QR Generator/QR_Generator.py
Labels: enhancement, hacktoberfest-accepted

#88 Create rock_paper_scissors.py
  Game/rock_paper_scissors.py
Labels: enhancement, hacktoberfest-accepted

#95 cc-validator.cpp
  CC Validator/cc-validator.cpp
Labels: enhancement, hacktoberfest

#91 Added a tinder clone website
  Tinder Clone/README.md
  Tinder Clone/css/styles.css
  Tinder Clone/example.html
  Tinder Clone/images/1298767_tinder_icon.png
  Tinder Clone/images/TechCrunch.png
  Tinder Clone/images/bizinsider.png
  Tinder Clone/images/dog-img.jpg
  Tinder Clone/images/iphone6.png
  Tinder Clone/images/lady-img.jpg
  Tinder Clone/images/mashable.png
  Tinder Clone/images/tnw.png
  Tinder Clone/index.html
Labels: enhancement, hacktoberfest

#96 Create Random Quote Generator Project
  Random Quote Generator/README.md
  Random Quote Generator/index.html
  Random Quote Generator/quote.js
  Random Quote Generator/script.js
  Random Quote Generator/style.css
Labels: enhancement, hacktoberfest

#99 Medical Commerce Website UI
  Medical Website/MANKINDLOGO.jpg
  Medical Website/abottlogo.png
  Medical Website/aciloc.jpg
  Medical Website/acnestar.png
  Medical Website/alkemlogo.png
  Medical Website/atozsyrup.jpg
  Medical Website/benadryl.jpg
  Medical Website/blucross.jpg
  Medical Website/bonepain.png
  Medical Website/bootstrap.css
  Medical Website/cart.html
  Medical Website/cipladinecream.jpg
  Medical Website/ciplalogo.png
  Medical Website/combiflam.jpg
  Medical Website/connect.php
  Medical Website/crocin.png
  Medical Website/dexorange.png
  Medical Website/doctors.png
  Medical Website/doctors1.jpg
  Medical Website/drredyy.jpg
  Medical Website/drypsingh.jpg
  Medical Website/drytndp.jpg
  Medical Website/hn5bpr1ci2do5kdub51v.png
  Medical Website/index.html
  Medical Website/index.js
  Medical Website/ipcalogo.jpg
  Medical Website/izmowfkjioi6zx103r85.png
  Medical Website/laboratelogo.jpg
  Medical Website/limcee.jpg
  Medical Website/lulibet.jpg
  Medical Website/mucaingelsyrup.png
  Medical Website/omnigel.jpg
  Medical Website/pain relief.png
  Medical Website/product-details.html
  Medical Website/product.html
  Medical Website/stomach care.png
  Medical Website/styles.css
Labels: enhancement, hacktoberfest

#100 Sorting Visualizer
  Sorting Visualizer/Sorting visualizer.py
  Sorting Visualizer/main.py
Labels: enhancement, hacktoberfest

#104 Calculator using JavaScript
  Calculator/app.js
  Calculator/index.html
  Calculator/style.css
Labels: enhancement, hacktoberfest

#107 added some style in navbar of medical website
  Medical Website/styles.css
Labels: enhancement, hacktoberfest

#110 Added a Dice game folder
  Dice Game/dicee.html
  Dice Game/images/dice1.png
  Dice Game/images/dice2.png
  Dice Game/images/dice3.png
  Dice Game/images/dice4.png
  Dice Game/images/dice5.png
  Dice Game/images/dice6.png
  Dice Game/images/favicon.ico
  Dice Game/index.js
  Dice Game/styles.css
Labels: enhancement, hacktoberfest

#111 resolved navbar issue
  Medical Website/styles.css
Labels: enhancement, hacktoberfest

#112 Rock paper scissors
  Rock Paper Scissor/index.html
  Rock Paper Scissor/paper.png
  Rock Paper Scissor/rock.png
  Rock Paper Scissor/scissors.png
  Rock Paper Scissor/script.js
  Rock Paper Scissor/style.css
Labels: enhancement, hacktoberfest

#113 added a night mode in analog clock website
  Analog Clock/index.html
  Analog Clock/style.css
Labels: enhancement, hacktoberfest

#116 Budget Check
  Budget Checker/.gitignore
  Budget Checker/build.gradle
  Budget Checker/gradle.properties
  Budget Checker/gradlew
  Budget Checker/gradlew.bat
  Budget Checker/ipcloudscs1.jpg
  Budget Checker/read.md
  Budget Checker/settings.gradle
Labels: enhancement, hacktoberfest

#118 Chat App using Node Js
  Chat-App/package-lock.json
  Chat-App/package.json
  Chat-App/server.js
Labels: enhancement, hacktoberfest

#121 Update of Chat App
  Chat-App/utils/messages.js
  Chat-App/utils/users.js
Labels: enhancement, hacktoberfest

#122 Added HTML files in Chat App
  Chat-App/public/chat.html
  Chat-App/public/index.html
Labels: enhancement, hacktoberfest

#124 Complete code of Chat App
  Chat-App/public/css/style.css
  Chat-App/public/js/main.js
Labels: enhancement, hacktoberfest

#127 Added copyright footer to analog clock index.html
  Analog Clock/index.html
Labels: enhancement, hacktoberfest

#128 Gift Selector
  Gift Selector/README.md
  Gift Selector/hint.md
  Gift Selector/index.css
  Gift Selector/index.html
  Gift Selector/index.js
  Gift Selector/package.json
  Gift Selector/webpack.config.js
Labels: enhancement, hacktoberfest

#131 all_occurences.cpp
  Method/all_occurences.cpp
Labels: enhancement, hacktoberfest

#135 palindrome_recursive.cpp
  Method/palindrome_recursive.cpp
Labels: enhancement, hacktoberfest

#134 30 days of javascript projects
  30 days of Javascript/01 - JSDrumKit/index.html
  30 days of Javascript/01 - JSDrumKit/style.css
  30 days of Javascript/Readme.md
Labels: enhancement, hacktoberfest

#136 sounds added
  30 days of Javascript/01 - JSDrumKit/sounds/bensound-funkyelement.mp3
  30 days of Javascript/01 - JSDrumKit/sounds/boom.wav
  30 days of Javascript/01 - JSDrumKit/sounds/clap.wav
  30 days of Javascript/01 - JSDrumKit/sounds/hihat.wav
  30 days of Javascript/01 - JSDrumKit/sounds/kick.wav
  30 days of Javascript/01 - JSDrumKit/sounds/openhat.wav
  30 days of Javascript/01 - JSDrumKit/sounds/ride.wav
  30 days of Javascript/01 - JSDrumKit/sounds/snare.wav
  30 days of Javascript/01 - JSDrumKit/sounds/tink.wav
  30 days of Javascript/01 - JSDrumKit/sounds/tom.wav
Labels: enhancement, hacktoberfest

#137 Js clock
  30 days of Javascript/02 - JSandCSSCLOCK/index.html
  30 days of Javascript/02 - JSandCSSCLOCK/main.js
  30 days of Javascript/02 - JSandCSSCLOCK/styles.css
Labels: enhancement, hacktoberfest

#138 Updated footer to the chat-app(hakctoberfest)
  Chat-App/public/chat.html
  Chat-App/public/css/style.css
  Chat-App/public/index.html
Labels: enhancement, hacktoberfest

#142 css vars with js
  30 days of Javascript/03 - CSSVariablesWithJS/index.html
  30 days of Javascript/03 - CSSVariablesWithJS/main.js
  30 days of Javascript/03 - CSSVariablesWithJS/styles.css
Labels: enhancement, hacktoberfest

#147 Create bookshop.cpp
  BookShop Management/bookshop.cpp
Labels: enhancement, hacktoberfest

#149 Create student_record.cpp
  Student Record/student_record.cpp
Labels: enhancement, hacktoberfest

#153 flex panel
  30 days of Javascript/05 - FlexPanelGallery/index.html
  30 days of Javascript/05 - FlexPanelGallery/main.js
  30 days of Javascript/05 - FlexPanelGallery/styles.css
Labels: enhancement, hacktoberfest

#155 array cardio 2
  30 days of Javascript/06 - ArrayCardioPartTwo/index.html
  30 days of Javascript/06 - ArrayCardioPartTwo/main.js
Labels: enhancement, hacktoberfest

#157 html canvas
  30 days of Javascript/07 - FunWithHTMLCanvas/index.html
  30 days of Javascript/07 - FunWithHTMLCanvas/main.js
Labels: enhancement, hacktoberfest

#172 some more javascript exercises
  30 days of Javascript/08 - Dev Tools Domination/index.html
  30 days of Javascript/09 - HoldShiftToCheckMultipleCheckboxes/index.html
  30 days of Javascript/10 - CustomHTML5VideoPlayer/index.html
  30 days of Javascript/10 - CustomHTML5VideoPlayer/main.mp4
  30 days of Javascript/10 - CustomHTML5VideoPlayer/scripts.js
  30 days of Javascript/10 - CustomHTML5VideoPlayer/style.css
Labels: enhancement, hacktoberfest

#178 Number-guess.py
  Game/number-guess.py
Labels: enhancement, hacktoberfest

#183 Online book store website
  repo-2-master/4star.jpg
  repo-2-master/5star.jpg
  repo-2-master/LOGO.jpg
  repo-2-master/b1.jpg
  repo-2-master/b2.jpg
  repo-2-master/b3.jpg
  repo-2-master/b4.jpg
  repo-2-master/b6.jpg
  repo-2-master/b7.jpg
  repo-2-master/b8.jpg
  repo-2-master/b9.jpg
  repo-2-master/book4.jpg
  repo-2-master/c1.jpg
  repo-2-master/c2.jpg
  repo-2-master/index.html
  repo-2-master/search.jpg
  repo-2-master/style.css
Labels: enhancement, hacktoberfest

#173 few more js exercises
  30 days of Javascript/11 - KeySequenceDetection/index.html
  30 days of Javascript/12 - Ajax Type Head/index.html
  30 days of Javascript/12 - Ajax Type Head/style.css
Labels: enhancement, hacktoberfest

#180 Diabetic Ratinopathy
  Ratinopathy.ipynb
Labels: enhancement, hacktoberfest

#182 15-puzzle-game
  15-puzzle-game-master/1.html
  15-puzzle-game-master/alert.js
  15-puzzle-game-master/jquery.js
  15-puzzle-game-master/puzzle.js
  15-puzzle-game-master/style.css
Labels: enhancement, hacktoberfest

#181 required modules .md
  Neural Network Visualization/app.py
  Neural Network Visualization/ml_server.py
  Neural Network Visualization/model.h5
  Neural Network Visualization/modelfile.ipynb
  Neural Network Visualization/required modules .md
Labels: enhancement, hacktoberfest

#161 Create Voice_Assistant.py
  Voice_Assistant.py
Labels: enhancement, hacktoberfest

#143 News app
  coffee-cafe website/HP.png
  coffee-cafe website/a.png
  coffee-cafe website/clients.jpg
  coffee-cafe website/coffee1.jpg
  coffee-cafe website/contact us.jpg
  coffee-cafe website/dd.jpg
  coffee-cafe website/dd1.jpg
  coffee-cafe website/delivery.jpg
  coffee-cafe website/images.png
  coffee-cafe website/index.html
  coffee-cafe website/l1.jpg
  coffee-cafe website/phone.css
  coffee-cafe website/style.css
  countdownTimer/index.html
  countdownTimer/script.js
  countdownTimer/style.css
  newsApp-master
Labels: enhancement, hacktoberfest

#193 Create readme.md
  Weather Guy/.gitignore
  Weather Guy/README.md
  Weather Guy/Weather App.iml
  Weather Guy/_gitignore
  Weather Guy/build.gradle
  Weather Guy/gradle.properties
  Weather Guy/gradlew
  Weather Guy/gradlew.bat
  Weather Guy/local.properties
  Weather Guy/readme.md
  Weather Guy/settings.gradle
Labels: enhancement, hacktoberfest

#192 Multiple face recognition
  Multiple Face recognition/.gitignore
  Multiple Face recognition/README.md
  Multiple Face recognition/face_rec.py
  Multiple Face recognition/faces.zip
  Multiple Face recognition/readme.md
  Multiple Face recognition/test.zip
Labels: enhancement, hacktoberfest

#191 Create read
  Workout/.gitignore
  Workout/README.md
  Workout/Seven Minute Workout.iml
  Workout/_gitignore
  Workout/build.gradle
  Workout/gradle.properties
  Workout/gradlew
  Workout/gradlew.bat
  Workout/local.properties
  Workout/read
  Workout/scui.png
  Workout/settings.gradle
Labels: enhancement, hacktoberfest

#194 added a reset button no need to refresh
  Dice Game/dicee.html
  Dice Game/index.js
  Dice Game/styles.css
Labels: enhancement, hacktoberfest

#198 Added Boston Model
  Boston_Houding_Model/Model.py
  Boston_Houding_Model/README.md
Labels: enhancement, hacktoberfest

#202 School Management System using Php and Database
  School Management System/add_class.php
  School Management System/add_staff.php
  School Management System/add_sub.php
  School Management System/admin_home.php
  School Management System/css/style.css
  School Management System/database.php
  School Management System/db/school (1).sql
  School Management System/delete.php
  School Management System/exam_delete.php
  School Management System/footer.php
  School Management System/img/Bg.png
  School Management System/img/home.jpg
  School Management System/index.php
  School Management System/js/jquery.js
  School Management System/logout.php
  School Management System/navbar.php
  School Management System/set_exam.php
  School Management System/sidebar.php
  School Management System/staff_delete.php
  School Management System/staff_view.php
  School Management System/sub_delete.php
  School Management System/view_exam.php
Labels: enhancement, hacktoberfest

#199 Added Notepad app uning python
  Notepad App/2.ico
  Notepad App/notepad.py
Labels: enhancement, good first issue, hacktoberfest

#208 Added a Ranfom Quote Generator Website that uses HTML ,CSS and JavaScript .
  Random_Quote_Generator/app.js
  Random_Quote_Generator/index.html
  Random_Quote_Generator/styles.css
Labels: enhancement, hacktoberfest

#207 calculator using vue
  The Calculator/public/Themes/Blue.css
  The Calculator/public/Themes/Green.css
  The Calculator/public/Themes/Light.css
  The Calculator/public/Themes/Yellow.css
  The Calculator/public/favicon.ico
  The Calculator/public/index.html
  The Calculator/public/manifest.json
  The Calculator/src/Components/Brand.css
  The Calculator/src/Components/Brand.jsx
  The Calculator/src/Components/Calculator.js
  The Calculator/src/Components/Calculator.test.js
  The Calculator/src/Components/Display.css
  The Calculator/src/Components/Display.jsx
  The Calculator/src/Components/Menu.jsx
  The Calculator/src/Components/Pads.css
  The Calculator/src/Components/Pads.jsx
  The Calculator/src/index.css
  The Calculator/src/index.js
  The Calculator/src/registerServiceWorker.js
Labels: enhancement, hacktoberfest

#210 Pomodoro Timer
  Pomodoro-main/README.md
  Pomodoro-main/index.html
  Pomodoro-main/main.js
  Pomodoro-main/style.css
Labels: enhancement, good first issue, hacktoberfest

#211 added instafilter
  Cupcake Corner/Cupcake Corner.xcodeproj/project.pbxproj
  Cupcake Corner/Cupcake Corner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Cupcake Corner/Cupcake Corner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Cupcake Corner/Cupcake Corner.xcodeproj/project.xcworkspace/xcuserdata/aarish.xcuserdatad/UserInterfaceState.xcuserstate
  Cupcake Corner/Cupcake Corner.xcodeproj/xcuserdata/aarish.xcuserdatad/xcschemes/xcschememanagement.plist
  Cupcake Corner/Cupcake Corner/AddressView.swift
  Cupcake Corner/Cupcake Corner/Assets.xcassets/AccentColor.colorset/Contents.json
  Cupcake Corner/Cupcake Corner/Assets.xcassets/AppIcon.appiconset/Contents.json
  Cupcake Corner/Cupcake Corner/Assets.xcassets/Contents.json
  Cupcake Corner/Cupcake Corner/Assets.xcassets/cupcakes.imageset/Contents.json
  Cupcake Corner/Cupcake Corner/Assets.xcassets/cupcakes.imageset/cupcakes@2x.jpg
  Cupcake Corner/Cupcake Corner/Assets.xcassets/cupcakes.imageset/cupcakes@3x.jpg
  Cupcake Corner/Cupcake Corner/CheckOutView.swift
  Cupcake Corner/Cupcake Corner/ContentView.swift
  Cupcake Corner/Cupcake Corner/Cupcake_CornerApp.swift
  Cupcake Corner/Cupcake Corner/Info.plist
  Cupcake Corner/Cupcake Corner/Order.swift
  Cupcake Corner/Cupcake Corner/Preview Content/Preview Assets.xcassets/Contents.json
  Cupcake Corner/Cupcake CornerTests/Cupcake_CornerTests.swift
  Cupcake Corner/Cupcake CornerTests/Info.plist
  Cupcake Corner/Cupcake CornerUITests/Cupcake_CornerUITests.swift
  Cupcake Corner/Cupcake CornerUITests/Info.plist
  InstaFilter/InstaFilter.xcodeproj/project.pbxproj
  InstaFilter/InstaFilter.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  InstaFilter/InstaFilter.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  InstaFilter/InstaFilter.xcodeproj/project.xcworkspace/xcuserdata/aarish.xcuserdatad/UserInterfaceState.xcuserstate
  InstaFilter/InstaFilter.xcodeproj/xcuserdata/aarish.xcuserdatad/xcschemes/xcschememanagement.plist
  InstaFilter/InstaFilter/Assets.xcassets/AccentColor.colorset/Contents.json
  InstaFilter/InstaFilter/Assets.xcassets/AppIcon.appiconset/Contents.json
  InstaFilter/InstaFilter/Assets.xcassets/Contents.json
  InstaFilter/InstaFilter/Assets.xcassets/Example.imageset/Contents.json
  InstaFilter/InstaFilter/Assets.xcassets/Example.imageset/jojosbr.png
  InstaFilter/InstaFilter/ContentView.swift
  InstaFilter/InstaFilter/ImagePicker.swift
  InstaFilter/InstaFilter/ImageSaver.swift
  InstaFilter/InstaFilter/InstaFilterApp.swift
  InstaFilter/InstaFilter/Preview Content/Preview Assets.xcassets/Contents.json
  InstaFilter/InstaFilterTests/InstaFilterTests.swift
  InstaFilter/InstaFilterUITests/InstaFilterUITests.swift
  InstaFilter/InstaFilterUITests/InstaFilterUITestsLaunchTests.swift
  InstaFilter/README.md
Labels: enhancement, hacktoberfest

#212 Log
  Log-main/project3.css
  Log-main/project3.html
Labels: enhancement, hacktoberfest

#213 added cupcake corner
  BetterRest/BetterRest.xcodeproj/project.pbxproj
  BetterRest/BetterRest.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  BetterRest/BetterRest.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  BetterRest/BetterRest.xcodeproj/project.xcworkspace/xcuserdata/aarish.xcuserdatad/UserInterfaceState.xcuserstate
  BetterRest/BetterRest.xcodeproj/xcuserdata/aarish.xcuserdatad/xcschemes/xcschememanagement.plist
  BetterRest/BetterRest/Assets.xcassets/AccentColor.colorset/Contents.json
  BetterRest/BetterRest/Assets.xcassets/AppIcon.appiconset/Contents.json
  BetterRest/BetterRest/Assets.xcassets/Contents.json
  BetterRest/BetterRest/BetterRestApp.swift
  BetterRest/BetterRest/ContentView.swift
  BetterRest/BetterRest/Info.plist
  BetterRest/BetterRest/Preview Content/Preview Assets.xcassets/Contents.json
  BetterRest/BetterRest/SleepCalculator.mlmodel
  BetterRest/BetterRestTests/BetterRestTests.swift
  BetterRest/BetterRestTests/Info.plist
  BetterRest/BetterRestUITests/BetterRestUITests.swift
  BetterRest/BetterRestUITests/Info.plist
Labels: enhancement, hacktoberfest

#216 Add files via upload
  Movie Recomender/README.md
  Movie Recomender/app.py
  Movie Recomender/notebook86c26b4f17.ipynb
Labels: enhancement, hacktoberfest

#206 Games using C++
  Games using C++/Asteroid.c.cpp
  Games using C++/DoodleJump.c.cpp
  Games using C++/Minesweeper.cpp.cpp
Labels: enhancement, hacktoberfest

#218 add image processing project that convert image colours
  image_Processing/imageProcessing.py
Labels: enhancement, hacktoberfest

#219 Create Dice_Roll_Simulator.py
  Dice_Roll_Simulator.py
Labels: enhancement, hacktoberfest

#220 Rotating Navigation Bar
  Rotating Navbar/project3.css
  Rotating Navbar/project3.html
  Rotating Navbar/project3.js
Labels: enhancement, hacktoberfest

#221 add and commit file
  lightLamp/index.html
  lightLamp/index.js
  lightLamp/lamp.png
  lightLamp/light.png
  lightLamp/logo.png
  lightLamp/menu.png
  lightLamp/style.css
Labels: enhancement, hacktoberfest

#222 Clock Website
  Clock/index.html
Labels: enhancement, hacktoberfest

#217 added an e-commerce coffee selling website
  e-commerce website/about-img.jpeg
  e-commerce website/blog-1.jpeg
  e-commerce website/blog-2.jpeg
  e-commerce website/blog-3.jpeg
  e-commerce website/cart-item-1.png
  e-commerce website/cart-item-2.png
  e-commerce website/cart-item-3.jpeg
  e-commerce website/cart-item-4.png
  e-commerce website/home-img.jpeg
  e-commerce website/index.html
  e-commerce website/logo.png
  e-commerce website/menu-1.png
  e-commerce website/menu-2.png
  e-commerce website/menu-3.png
  e-commerce website/menu-4.png
  e-commerce website/menu-5.png
  e-commerce website/menu-6.png
  e-commerce website/pic-1.png
  e-commerce website/pic-2.png
  e-commerce website/pic-3.png
  e-commerce website/product-1.png
  e-commerce website/product-2.png
  e-commerce website/product-3.png
  e-commerce website/quote-img.png
  e-commerce website/style.css
Labels: enhancement, hacktoberfest

#225 Painting App
  Painting App/index.html
  Painting App/script.js
  Painting App/style.css
Labels: enhancement, hacktoberfest

#227 Calendar
  Calendar_UI/index.html
  Calendar_UI/script.js
  Calendar_UI/style.css
Labels: enhancement
